name: cicd

on:
  push:
    paths:
      - src/**
    branchs:
      - main

jobs:
  ci:
    outputs: 
      commit_id: ${{ steps.vars.outputs.sha_short }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mgsantos89/python-app:${{ steps.vars.outputs.sha_short }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    
    steps:


      -
        name: Modify values
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          sudo apt update
          sudo apt install python3 python3-pip -y
          pip install yq --break-system-packages
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/values.yaml
      -
        name: argo-cli install
        shell: bash
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd 

      -
        name: argocd login
        shell: bash
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --insecure --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}

      -
        name: argocd sync app
        shell: bash
        run: |
          argocd app sync python-app

